---
name: First YAML document

tags: TTAST_TAGS

original_filename: {{ import_filename | default('Unknown') }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test

name: Second document in first.yaml

value: test

test1: |
  this
  is
  a
  test

test2: >
  another test
  here
