vars:
  replace_value: 100

pipeline:

  - stdin: {}
    apply_tags:
      - stdin
      - "{{ import_tag }}"

  - import:
      files:
        - "example/files/**/*.yaml"
      recursive: true
    apply_tags:
      - yaml
      - import
      - "{{ import_tag }}"

  - replace:
      items:
        - key: REPLACE_VALUE_HERE
          value: "{{ replace_value / 2 }}"
        - key: "Y..."
          value: "{{ other_replacement }}"
          regex: true
        - key: "TTAST_TAGS"
          value: "{{ ttast_tags }}"

  - template:
      vars:
        override: frog
    match_any_tags:
      - import
    apply_tags:
      - templated

  - template:
      vars:
        override: "{{ other_replacement }}"
    exclude_tags:
      - templated
    apply_tags:
      - templated

  - vars:
      block:
        document_type: yaml
    match_any_tags:
      - yaml

  - jsonpatch:
      patches:
        - op: add
          path: "/metadata/annotations"
          value: {}
        - op: add
          path: "/metadata/annotations/test"
          value: 10
        - op: add
          path: "/metadata/annotations/other"
          value: 12
    match_kind: "StatefulSet|Deployment"

  - sum: {}

  - metadata:
      namespace: tester
      name: "{{ metadata_name|default('unknown') + '-' + shortsum }}"
      labels:
        app: appname

  - metadata:
      annotations:
        reloader.stakater.com/auto: "true"
    when:
      - 'metadata_kind in ["DaemonSet", "StatefulSet", "Deployment"]'

  - metadata:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    when:
      - 'metadata_kind in ["Ingress"]'
